//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVentaReparacionDeCelulares.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio
    {
        public int id_envio { get; set; }
        public int id_venta { get; set; }
        public string direccion_envio { get; set; }
        public string ciudad_envio { get; set; }
        public string estado_envio { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<System.DateTime> fecha_entrega_estimada { get; set; }
    
        public virtual VentaMarketplace VentaMarketplace { get; set; }
    }
}
