//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVentaReparacionDeCelulares.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaMarketplace
    {
        public int id_factura { get; set; }
        public int id_venta { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public Nullable<decimal> total_pagado { get; set; }
        public Nullable<decimal> total_proveedor { get; set; }
        public Nullable<decimal> total_comision { get; set; }
    
        public virtual VentaMarketplace VentaMarketplace { get; set; }
    }
}
