//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVentaReparacionDeCelulares.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportacionProducto
    {
        public int id_importacion { get; set; }
        public int id_producto_proveedor { get; set; }
        public string pais_origen { get; set; }
        public Nullable<System.DateTime> fecha_importacion { get; set; }
        public string numero_guia { get; set; }
        public string aduana { get; set; }
    
        public virtual ProductoProveedor ProductoProveedor { get; set; }
    }
}
