//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVentaReparacionDeCelulares.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoProveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductoProveedor()
        {
            this.DetallePedidoProveedors = new HashSet<DetallePedidoProveedor>();
            this.DetalleVentaMarketplaces = new HashSet<DetalleVentaMarketplace>();
            this.Garantias = new HashSet<Garantia>();
            this.ImportacionProductoes = new HashSet<ImportacionProducto>();
            this.MovimientoStocks = new HashSet<MovimientoStock>();
        }
    
        public int id_producto_proveedor { get; set; }
        public int id_usuario_proveedor { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion { get; set; }
        public decimal precio_unitario { get; set; }
        public Nullable<int> stock_disponible { get; set; }
        public Nullable<int> garantia_meses { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> vendido_por_empresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedidoProveedor> DetallePedidoProveedors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVentaMarketplace> DetalleVentaMarketplaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Garantia> Garantias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportacionProducto> ImportacionProductoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoStock> MovimientoStocks { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
