//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVentaReparacionDeCelulares.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoporteCliente
    {
        public int id_soporte { get; set; }
        public int id_usuario_cliente { get; set; }
        public string asunto { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public string estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
