//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVentaReparacionDeCelulares.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaMarketplace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VentaMarketplace()
        {
            this.DetalleVentaMarketplaces = new HashSet<DetalleVentaMarketplace>();
            this.Envios = new HashSet<Envio>();
            this.FacturaMarketplaces = new HashSet<FacturaMarketplace>();
            this.Garantias = new HashSet<Garantia>();
            this.PagoVentas = new HashSet<PagoVenta>();
        }
    
        public int id_venta { get; set; }
        public int id_usuario_cliente { get; set; }
        public Nullable<System.DateTime> fecha_venta { get; set; }
        public Nullable<decimal> monto_total { get; set; }
        public Nullable<decimal> comision_empresa { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVentaMarketplace> DetalleVentaMarketplaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Envio> Envios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaMarketplace> FacturaMarketplaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Garantia> Garantias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoVenta> PagoVentas { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
