//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVentaReparacionDeCelulares.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VentaYReparacionDeCelulares1Entities : DbContext
    {
        public VentaYReparacionDeCelulares1Entities()
            : base("name=VentaYReparacionDeCelulares1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ciudad> Ciudads { get; set; }
        public virtual DbSet<DetallePedidoProveedor> DetallePedidoProveedors { get; set; }
        public virtual DbSet<DetalleReparacion> DetalleReparacions { get; set; }
        public virtual DbSet<DetalleVentaMarketplace> DetalleVentaMarketplaces { get; set; }
        public virtual DbSet<Envio> Envios { get; set; }
        public virtual DbSet<FacturaCompra> FacturaCompras { get; set; }
        public virtual DbSet<FacturaMarketplace> FacturaMarketplaces { get; set; }
        public virtual DbSet<Garantia> Garantias { get; set; }
        public virtual DbSet<ImportacionProducto> ImportacionProductoes { get; set; }
        public virtual DbSet<MetodoPago> MetodoPagoes { get; set; }
        public virtual DbSet<MovimientoStock> MovimientoStocks { get; set; }
        public virtual DbSet<PagoVenta> PagoVentas { get; set; }
        public virtual DbSet<Pai> Pais { get; set; }
        public virtual DbSet<PedidoProveedor> PedidoProveedors { get; set; }
        public virtual DbSet<ProductoProveedor> ProductoProveedors { get; set; }
        public virtual DbSet<Sede> Sedes { get; set; }
        public virtual DbSet<ServicioReparacion> ServicioReparacions { get; set; }
        public virtual DbSet<SoporteCliente> SoporteClientes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tecnico> Tecnicoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<VentaMarketplace> VentaMarketplaces { get; set; }
    }
}
